# Generated by Django 4.2.23 on 2025-09-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0059_alter_capturejob_creation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='validation_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
