# Generated by Django 4.2.23 on 2025-12-17 18:08

from django.db import migrations

SWITCH_NAME = "use_beta_capture_api"

def create_capture_api_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    switch = Switch(
        name=SWITCH_NAME,
        active=False
    )
    switch.save()

def delete_capture_api_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    switches = Switch.objects.filter(name=SWITCH_NAME)
    switches.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0061_auto_20251217_1808'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(create_capture_api_switch, delete_capture_api_switch),
    ]
