# Generated by Django 4.2.23 on 2026-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0062_auto_20260114_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
