# Generated by Django 4.2.23 on 2026-06-18 17:01

from django.db import migrations

SWITCH_NAME = "use_stripe_payments_app"

def create_payments_app_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    switch = Switch(
        name=SWITCH_NAME,
        active=False
    )
    switch.save()

def delete_payments_app_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    switches = Switch.objects.filter(name=SWITCH_NAME)
    switches.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0063_historicalregistrar_notes_registrar_notes'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(create_payments_app_switch, delete_payments_app_switch),
    ]
