# Generated by Django 4.2.23 on 2026-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0063_historicalregistrar_notes_registrar_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='internet_archive_upload_status',
            field=models.CharField(choices=[('deletion_required', 'deletion_required'), ('upload_or_reupload_required', 'upload_or_reupload_required')], db_index=True, max_length=28, null=True),
        ),
    ]
