# Generated by Django 4.2.23 on 2026-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0065_historicalregistrar_type_registrar_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrar',
            name='international',
            field=models.BooleanField(default=False),
        ),
    ]
