# Generated by Django 4.2.23 on 2026-06-30 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0066_historicalregistrar_international_registrar_international'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrar',
            name='international',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('law-library', 'Law library'), ('academic-library', 'Academic library'), ('other-library', 'Other library'), ('law-firm', 'Law firm'), ('court', 'Court'), ('public-defender', 'Public defender'), ('attorney-general', 'Attorney general'), ('government', 'Government'), ('nonprofit', 'Nonprofit'), ('factcheck', 'Factcheck'), ('news/journalism', 'News/journalism'), ('other-org', 'Other org')], max_length=20), blank=True, db_index=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='international',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('law-library', 'Law library'), ('academic-library', 'Academic library'), ('other-library', 'Other library'), ('law-firm', 'Law firm'), ('court', 'Court'), ('public-defender', 'Public defender'), ('attorney-general', 'Attorney general'), ('government', 'Government'), ('nonprofit', 'Nonprofit'), ('factcheck', 'Factcheck'), ('news/journalism', 'News/journalism'), ('other-org', 'Other org')], max_length=20), blank=True, db_index=True, default=list, size=None),
        ),
    ]
