# Generated by Django 4.2.23 on 2026-07-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0068_auto_20260714_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='local_subscription_description',
            field=models.TextField(blank=True, default='', help_text="Special text that appears on the usage plan page, describing this customer's subscription."),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='local_subscription_description',
            field=models.TextField(blank=True, default='', help_text="Special text that appears on the usage plan page, describing this customer's subscription."),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='local_subscription_description',
            field=models.TextField(blank=True, default='', help_text="Special text that appears on the usage plan page, describing this customer's subscription."),
        ),
        migrations.AddField(
            model_name='registrar',
            name='local_subscription_description',
            field=models.TextField(blank=True, default='', help_text="Special text that appears on the usage plan page, describing this customer's subscription."),
        ),
    ]
