# Generated by Django 4.2.23 on 2026-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0069_historicallinkuser_local_subscription_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='frozen',
            field=models.BooleanField(default=False, help_text='If frozen, this account cannot create links regardless of subscription or bonus links. Set when enforcing a dispute or refund; clear to restore access.'),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='frozen',
            field=models.BooleanField(default=False, help_text='If frozen, this account cannot create links regardless of subscription or bonus links. Set when enforcing a dispute or refund; clear to restore access.'),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='frozen',
            field=models.BooleanField(default=False, help_text='If frozen, this account cannot create links regardless of subscription or bonus links. Set when enforcing a dispute or refund; clear to restore access.'),
        ),
        migrations.AddField(
            model_name='registrar',
            name='frozen',
            field=models.BooleanField(default=False, help_text='If frozen, this account cannot create links regardless of subscription or bonus links. Set when enforcing a dispute or refund; clear to restore access.'),
        ),
    ]
