# Generated by Django 4.2.23 on 2026-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0070_historicallinkuser_frozen_historicalregistrar_frozen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='grandfathered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='grandfathered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='grandfathered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrar',
            name='grandfathered',
            field=models.BooleanField(default=False),
        ),
    ]
