# Generated by Django 4.2.23 on 2026-07-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0071_historicallinkuser_grandfathered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='offer_annual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicallinkuser',
            name='offer_monthly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='offer_annual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='offer_monthly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='offer_annual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='offer_monthly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='offer_annual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='offer_monthly',
            field=models.BooleanField(default=True),
        ),
    ]
