# Generated by Django 4.2.23 on 2026-07-31 13:42

from django.db import migrations

SWITCH_NAME = "show_generic_payment_banner"

def create_banner_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    switch = Switch(
        name=SWITCH_NAME,
        active=True
    )
    switch.save()

def delete_banner_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    switches = Switch.objects.filter(name=SWITCH_NAME)
    switches.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0072_historicallinkuser_offer_annual_and_more'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(create_banner_switch, delete_banner_switch),
    ]
