# Generated by Django 4.2.23 on 2026-08-04 15:57

from django.db import migrations

STRIPE_SWITCH_NAME = "use_stripe_payments_app"
MESSAGE_SWITCH_NAME = "display_cybersource_freeze_message"
CYBERSOURCE_SWITCH_NAME = "allow_cybersource_transactions"
BANNER_SWITCH_NAME = "show_generic_payment_banner"


def create_switch(apps, switch_name, active=False):
    Switch = apps.get_model("waffle", "Switch")
    switch = Switch(
        name=switch_name,
        active=active
    )
    switch.save()

def delete_switch(apps, switch_name):
    Switch = apps.get_model("waffle", "Switch")
    switches = Switch.objects.filter(name=switch_name)
    switches.delete()

def create_stripe_switch(apps, schema_editor):
    create_switch(apps, STRIPE_SWITCH_NAME, active=True)

def delete_stripe_switch(apps, schema_editor):
    delete_switch(apps, STRIPE_SWITCH_NAME)

def create_message_switch(apps, schema_editor):
    create_switch(apps, MESSAGE_SWITCH_NAME)

def delete_message_switch(apps, schema_editor):
    delete_switch(apps, MESSAGE_SWITCH_NAME)

def create_cybersource_switch(apps, schema_editor):
    create_switch(apps, CYBERSOURCE_SWITCH_NAME)

def delete_cybersource_switch(apps, schema_editor):
    delete_switch(apps, CYBERSOURCE_SWITCH_NAME)

def create_banner_switch(apps, schema_editor):
    create_switch(apps, BANNER_SWITCH_NAME)

def delete_banner_switch(apps, schema_editor):
    delete_switch(apps, BANNER_SWITCH_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0073_auto_20260731_1342'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(delete_stripe_switch, create_stripe_switch),
        migrations.RunPython(delete_message_switch, create_message_switch),
        migrations.RunPython(delete_cybersource_switch, create_cybersource_switch),
        migrations.RunPython(delete_banner_switch, create_banner_switch),
    ]
