# Generated by Django 4.2.23 on 2026-08-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0074_auto_20260804_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallinkuser',
            name='grandfathered',
        ),
        migrations.RemoveField(
            model_name='historicalregistrar',
            name='grandfathered',
        ),
        migrations.RemoveField(
            model_name='linkuser',
            name='grandfathered',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='grandfathered',
        ),
    ]
