# Generated by Django 4.2.23 on 2026-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0075_remove_historicallinkuser_grandfathered_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['created_by', 'user_deleted'], name='perma_link_created_f1b17f_idx'),
        ),
    ]
